#!/usr/bin/env python3
"""Write a short, self-describing README for one automated snapshot run.

Usage: write_snapshot_readme.py <snapshot_dir>
Run with cwd = research/2026-09-16-cross-lender-exit (snapshot.yml does this),
so <snapshot_dir> is relative to that folder, e.g. snapshots/2026-09-18T0530Z.
"""
import json
import sys
from pathlib import Path

snap_dir = Path(sys.argv[1])
sellable = json.loads((snap_dir / "sellable.json").read_text())
rows = sellable["rows"]
fetched_at = sellable["fetched_at"]

# STRCx's Token-2022 UI multiplier makes its quotes inconsistent (see the
# parent README) — excluded from totals the same way the manual runs are.
priced = {m: r for m, r in rows.items() if r["symbol"] != "STRCx" and r["pledged_usd"] >= 1000}
pledged = sum(r["pledged_usd"] for r in priced.values())
sellable5 = sum(min(r["sellable"]["5pct"], r["pledged_usd"]) for r in priced.values())
coverage = sellable5 / pledged if pledged else 0

lines = [
    f"# Automated snapshot — {fetched_at}",
    "",
    f"**${pledged:,.0f} pledged across Kamino and Jupiter Lend. "
    f"${sellable5:,.0f} sellable within 5% of its price ({coverage*100:.1f}%).**",
    "",
    "Generated by `.github/workflows/snapshot.yml` — same method as the parent "
    "study (`../README.md`): pledged collateral per token, then a Jupiter sell "
    "ladder from $1,000 to $16M, with the gap bisected when a route ends between "
    "two ladder steps.",
    "",
    "| Token | Pledged | Sellable @1% | Sellable @5% | Sellable @10% | Route ends at |",
    "|---|---|---|---|---|---|",
]
for m, r in sorted(priced.items(), key=lambda kv: -kv[1]["pledged_usd"]):
    s = r["sellable"]
    nr = next((p for p in r["points"] if p.get("no_route")), None)
    ends = f"${nr['usd_in']:,.0f}" if nr else "—"
    lines.append(
        f"| {r['symbol']} | ${r['pledged_usd']:,.0f} | ${s['1pct']:,.0f} "
        f"| ${s['5pct']:,.0f} | ${s['10pct']:,.0f} | {ends} |"
    )

lines += [
    "",
    "STRCx excluded from totals (Token-2022 UI multiplier makes its quotes "
    "inconsistent — see the parent README).",
    "",
    "Raw data: `collateral.json`, `sellable.json`, `summary.txt` in this folder.",
]

(snap_dir / "README.md").write_text("\n".join(lines) + "\n")
print(f"wrote {snap_dir / 'README.md'}")
